require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DemosController do

  # This should return the minimal set of attributes required to create a valid
  # Demo. As you add validations to Demo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all demos as @demos" do
      demo = Demo.create! valid_attributes
      get :index
      assigns(:demos).should eq([demo])
    end
  end

  describe "GET show" do
    it "assigns the requested demo as @demo" do
      demo = Demo.create! valid_attributes
      get :show, :id => demo.id.to_s
      assigns(:demo).should eq(demo)
    end
  end

  describe "GET new" do
    it "assigns a new demo as @demo" do
      get :new
      assigns(:demo).should be_a_new(Demo)
    end
  end

  describe "GET edit" do
    it "assigns the requested demo as @demo" do
      demo = Demo.create! valid_attributes
      get :edit, :id => demo.id.to_s
      assigns(:demo).should eq(demo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Demo" do
        expect {
          post :create, :demo => valid_attributes
        }.to change(Demo, :count).by(1)
      end

      it "assigns a newly created demo as @demo" do
        post :create, :demo => valid_attributes
        assigns(:demo).should be_a(Demo)
        assigns(:demo).should be_persisted
      end

      it "redirects to the created demo" do
        post :create, :demo => valid_attributes
        response.should redirect_to(Demo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved demo as @demo" do
        # Trigger the behavior that occurs when invalid params are submitted
        Demo.any_instance.stub(:save).and_return(false)
        post :create, :demo => {}
        assigns(:demo).should be_a_new(Demo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Demo.any_instance.stub(:save).and_return(false)
        post :create, :demo => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested demo" do
        demo = Demo.create! valid_attributes
        # Assuming there are no other demos in the database, this
        # specifies that the Demo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Demo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => demo.id, :demo => {'these' => 'params'}
      end

      it "assigns the requested demo as @demo" do
        demo = Demo.create! valid_attributes
        put :update, :id => demo.id, :demo => valid_attributes
        assigns(:demo).should eq(demo)
      end

      it "redirects to the demo" do
        demo = Demo.create! valid_attributes
        put :update, :id => demo.id, :demo => valid_attributes
        response.should redirect_to(demo)
      end
    end

    describe "with invalid params" do
      it "assigns the demo as @demo" do
        demo = Demo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Demo.any_instance.stub(:save).and_return(false)
        put :update, :id => demo.id.to_s, :demo => {}
        assigns(:demo).should eq(demo)
      end

      it "re-renders the 'edit' template" do
        demo = Demo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Demo.any_instance.stub(:save).and_return(false)
        put :update, :id => demo.id.to_s, :demo => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested demo" do
      demo = Demo.create! valid_attributes
      expect {
        delete :destroy, :id => demo.id.to_s
      }.to change(Demo, :count).by(-1)
    end

    it "redirects to the demos list" do
      demo = Demo.create! valid_attributes
      delete :destroy, :id => demo.id.to_s
      response.should redirect_to(demos_url)
    end
  end

end
